FROM python:3.10-slim

# Copia o código para dentro do container
COPY run.py /run.py

# Instala dependências necessárias (exemplo)
RUN pip install rustplus

# Comando para iniciar o script
CMD ["python", "/run.py"]
